name: RemoteGUI
version: '${version}'
main: top.jingwenmc.remotegui.bukkit.RemoteGUIBukkit
depend: [ MQEasy ]
authors: [ jingwenMC ]
description: Send player a gui on bungee!
website: www.jingwenmc.top
